// What happens when you run the following program? Why do we get that result?

// {
//   let foo = 'bar';
// }

// console.log(foo);

// Raise an error bc foo is declared in within the block, thus it cannot
// be accessed from outside the scope of the block.